apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolibarr
  template:
    metadata:
      labels:
        app: dolibarr
    spec:
      containers:
      - name: dolibarr
        image: dolibarr/dolibarr:latest
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "dolibarr"
        - name: DB_USER
          value: "dolibarruser"
        - name: DB_PASSWORD
          value: "dolibarrpassword"
        ports:
        - containerPort: 80

        # Ajout des probes de santé
        livenessProbe:
          httpGet:
            path: /  # Chemin à vérifier pour l'état de santé
            port: 80
          initialDelaySeconds: 60  # Attendre 60 secondes avant de vérifier
          periodSeconds: 30  # Vérifier toutes les 30 secondes

        readinessProbe:
          httpGet:
            path: /  # Chemin à vérifier pour vérifier si le service est prêt
            port: 80
          initialDelaySeconds: 30  # Attendre 30 secondes avant de vérifier
          periodSeconds: 10  # Vérifier toutes les 10 secondes

---
apiVersion: v1
kind: Service
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dolibarr
