apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dolibarr
  template:
    metadata:
      labels:
        app: dolibarr
    spec:
      containers:
      - name: dolibarr
        image: dolibarr/dolibarr:latest
        env:
        - name: DOLI_DB_HOST
          value: "mysql"
        - name: DOLI_DB_NAME
          value: "dolibarr"
        - name: DOLI_DB_USER
          value: "dolibarruser"
        - name: DOLI_DB_PASSWORD
          value: "dolibarrpassword"
        # - name: DOLI_URL_ROOT
        #   value: "http://0.0.0.0"
        # - name: DOLI_ADMIN_LOGIN
        #   value: "admin"
        # - name: DOLI_ADMIN_PASSWORD
        #   value: "adminpassword"
        # - name: DOLI_INIT_DEMO
        #   value: 0
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /var/www/documents
          name: dolibarr-documents
        - mountPath: /var/www/html/custom
          name: dolibarr-custom
      volumes:
      - name: dolibarr-documents
        persistentVolumeClaim:
          claimName: dolibarr-documents-pvc
      - name: dolibarr-custom
        persistentVolumeClaim:
          claimName: dolibarr-custom-pvc
          
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 40

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30050
  selector:
    app: dolibarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolibarr-documents-pvc
  namespace: dolibarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolibarr-custom-pvc
  namespace: dolibarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
